kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${BACKUP_POSTGRESQL_APP_NAME}-build-template
  creationTimestamp: null
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${BACKUP_POSTGRESQL_APP_NAME}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${BACKUP_POSTGRESQL_APP_NAME}
      labels:
        app: ${BACKUP_POSTGRESQL_APP_NAME}
    spec:
      triggers:
        - type: ImageChange
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: ${GIT_REPO_URL}
          ref: ${GIT_REF}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Docker
        dockerStrategy:
          pullSecret:
            name: artifacts-pull-default-hkucak
          from:
            kind: DockerImage
            name: ${BASE_IMAGE_FOR_BUILD}
          dockerfilePath: ${DOCKER_FILE_PATH}
      output:
        to:
          kind: ImageStreamTag
          name: ${BACKUP_POSTGRESQL_APP_NAME}:${OUTPUT_IMAGE_TAG}
      resources:
        limits:
          cpu: '250m'
          memory: 1Gi
        requests:
          cpu: '50m'
          memory: '256Mi'
parameters:
  - name: BACKUP_POSTGRESQL_APP_NAME
    displayName: BACKUP POSTGRESQL APP NAME
    description: The name assigned to all of the resources.  Use 'backup-{database name}' depending on your database provider
    required: true
    value: backup-postgres-app-name
  - name: GIT_REPO_URL
    displayName: Git Repo URL
    description: The URL to your GIT repo.
    required: true
    value: https://github.com/BCDevOps/backup-container.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: master
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: /docker
  - name: DOCKER_FILE_PATH
    displayName: Docker File
    description: The path and file of the docker file defining the build.  Choose either 'Dockerfile' for Postgres builds or 'Dockerfile_Mongo' for MongoDB builds or 'Dockerfile_MSSQL' for MSSQL builds.
    required: false
    value: Dockerfile
  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest
  - name: BASE_IMAGE_FOR_BUILD
    displayName: FROM Image Tag
    description: Base image to build from.  Docker creds or Artificatory setup may be needed to alleviate docker rate-limiting
    required: true
    value: artifacts.developer.gov.bc.ca/docker-remote/fedora/postgresql-14:14
