# Generalised template for building from Dockerfile in a git repo.
# Includes importing the base image as an imagestream.
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${PATRONI_NAME}
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: ${BASE_IMAGE_NAME}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: ImageStreamTag
    lookupPolicy:
      local: false
    metadata:
      name: ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}
    tag:
      annotations: null
      from:
        kind: DockerImage
        name: ${BASE_IMAGE_REPO}${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${PATRONI_NAME}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${PATRONI_NAME}
    spec:
      resources:
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
        requests:
          cpu: ${CPU_REQUEST}
          memory: ${MEMORY_REQUEST}
      output:
        to:
          kind: ImageStreamTag
          name: "${PATRONI_NAME}:${TAG}"
      runPolicy: SerialLatestOnly
      source:
        contextDir: /openshift/patroni-postgres-container
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}
        type: Docker
parameters:
  - name: PATRONI_NAME
    required: true
  - name: SOURCE_REPOSITORY_URL
    required: true
    value: https://github.com/bcgov/usp.git
  - name: SOURCE_REPOSITORY_REF
    required: true
  - name: TAG
    value: "latest"
  - name: BASE_IMAGE_REPO
  - name: BASE_IMAGE_NAME
    required: true
  - name: BASE_IMAGE_TAG
    required: true
  - name: CPU_LIMIT
    value: "500m"
  - name: MEMORY_LIMIT
    value: "1Gi"
  - name: CPU_REQUEST
    value: "100m"
  - name: MEMORY_REQUEST
    value: "500m"
  - name: ARG_KEY_1
    value: __DUMMY_1
  - name: ARG_KEY_2
    value: __DUMMY_2
  - name: ARG_KEY_3
    value: __DUMMY_3
  - name: ARG_KEY_4
    value: __DUMMY_4
  - name: ARG_VAL_1
  - name: ARG_VAL_2
  - name: ARG_VAL_3
  - name: ARG_VAL_4
